version: "3.7"

services:
  kirby:
    build:
      context: ./
      args:
        - BASE_IMAGE_NAME=${BASE_IMAGE_NAME}
    networks:
      - chissmiii

networks:
  chissmiii:
    driver: bridge
    name: chissmiii_network
