version: "3.7"

services:
  chissmiii-kirby:
    image: chissmiii_kirby:dev
    build:
      context: ./
    container_name: chissmiii_kirby
    networks:
      - chissmiii

networks:
  chissmiii:
    driver: bridge
    name: chissmiii_network
