version: "3.7"

services:
  chissmiii-kirby:
    image: chissmiii_kirby:prod
    restart: unless-stopped
    command: sh -c "apache2-foreground"
    ports:
      - 14080:80
      - 14443:443
    volumes:
      - chissmiii_kirby_content_vol:/var/www/html/content
      - chissmiii_kirby_media_vol:/var/www/html/media
      - chissmiii_kirby_node_modules_vol:/var/www/html/node_modules
      - chissmiii_kirby_site_vol:/var/www/html/site
      - chissmiii_kirby_src_vol:/var/www/html/src

volumes:
  chissmiii_kirby_content_vol:
    name: chissmiii_kirby_content
    driver: local
    driver_opts:
      device: /var/www/chissmiii_vols/content
      type: none
      o: bind

  chissmiii_kirby_media_vol:
    name: chissmiii_kirby_media
    driver: local
    driver_opts:
      device: /var/www/chissmiii_vols/media
      type: none
      o: bind

  chissmiii_kirby_node_modules_vol:
    name: chissmiii_kirby_node_modules
    driver: local
    driver_opts:
      device: /var/www/chissmiii_vols/node_modules
      type: none
      o: bind

  chissmiii_kirby_site_vol:
    name: chissmiii_kirby_site
    driver: local
    driver_opts:
      device: /var/www/chissmiii/dist/site/
      type: none
      o: bind

  chissmiii_kirby_src_vol:
    name: chissmiii_kirby_src
    driver: local
    driver_opts:
      device: /var/www/chissmiii/dist/src
      type: none
      o: bind
