version: "3.7"

services:
  kirby:
    image: ${COMPOSE_PROJECT_NAME}_kirby:dev
    build:
      dockerfile: Dockerfile.dev
    container_name: ${MAIN_CONTAINER_NAME}-dev
    restart: "no"
    ports:
      - 8000:80
    volumes:
      - dist:/var/www/html
      - ${EXTERNAL_VOLUMES_PATH}/cloud:/cloud
      - ${EXTERNAL_VOLUMES_PATH}/kirby-content:/var/www/html/content

volumes:

  dist:
    driver: local
    driver_opts:
      device: ${PWD}/dist
      type: none
      o: bind