version: "3.7"

services:
  kirby:
    image: ${COMPOSE_PROJECT_NAME}_kirby:prod
    build:
      dockerfile: Dockerfile.prod
    container_name: ${MAIN_CONTAINER_NAME}-prod
    restart: unless-stopped
    ports:
      - 14080:80
      - 14443:443
    volumes:
      - kirby_content:/var/www/html/content
      - kirby_media:/var/www/html/media
      - node_modules:/var/www/html/node_modules
      - kirby_site:/var/www/html/site
      - kirby_accounts:/var/www/html/site/accounts
      - kirby_sessions:/var/www/html/site/sessions
      - resources_src:/var/www/html/src
      - resources_dist_js:/var/www/html/resources/js
      - resources_dist_css:/var/www/html/resources/css

volumes:

  node_modules:

  resources_src:
    driver: local
    driver_opts:
      device: ${PWD}/dist/src
      type: none
      o: bind

  resources_dist_js:

  resources_dist_css:

  kirby_content:
    driver: local
    driver_opts:
      device: ${PWD}/dist/content
      type: none
      o: bind

  kirby_media:
    driver: local
    driver_opts:
      device: ${EXTERNAL_VOLUMES_PATH}/media
      type: none
      o: bind

  kirby_site:
    driver: local
    driver_opts:
      device: ${PWD}/dist/site/
      type: none
      o: bind

  kirby_accounts:
    driver: local
    driver_opts:
      device: ${EXTERNAL_VOLUMES_PATH}/site/accounts
      type: none
      o: bind

  kirby_sessions:
