version: "3.7"

services:
  kirby:
    image: ${COMPOSE_PROJECT_NAME}_kirby:prod
    build:
      dockerfile: Dockerfile.prod
    container_name: ${MAIN_CONTAINER_NAME}-prod
    restart: unless-stopped
    ports:
      - 14080:80
      - 14443:443
    volumes:
      - kirby_content_vol:/var/www/html/content
      - kirby_media_vol:/var/www/html/media
      - node_modules_vol:/var/www/html/node_modules
      - kirby_site_vol:/var/www/html/site
      - kirby_accounts_vol:/var/www/html/site/accounts
      - kirby_sessions_vol:/var/www/html/site/sessions
      - resources_src_vol:/var/www/html/src

volumes:
  kirby_content_vol:
    driver: local
    driver_opts:
      device: ${PWD}/dist/content
      type: none
      o: bind

  kirby_media_vol:
    driver: local
    driver_opts:
      device: ${EXTERNAL_VOLUMES_PATH}/media
      type: none
      o: bind

  node_modules_vol:
    driver: local
    driver_opts:
      device: ${EXTERNAL_VOLUMES_PATH}/node_modules
      type: none
      o: bind

  kirby_site_vol:
    driver: local
    driver_opts:
      device: ${PWD}/dist/site/
      type: none
      o: bind

  kirby_accounts_vol:
    driver: local
    driver_opts:
      device: ${EXTERNAL_VOLUMES_PATH}/site/accounts
      type: none
      o: bind

  kirby_sessions_vol:
    driver: local
    driver_opts:
      device: ${EXTERNAL_VOLUMES_PATH}/site/sessions
      type: none
      o: bind

  resources_src_vol:
    driver: local
    driver_opts:
      device: ${PWD}/dist/src
      type: none
      o: bind
