version: "3.7"

services:
  kirby:
    build:
      context: ./
    container_name: chissmiii_kirby
    networks:
      - chissmiii

networks:
  chissmiii:
    driver: bridge
    name: chissmiii_network
