version: "3.7"

services:
  kirby:
    image: chissmiii_kirby:dev
    build:
      dockerfile: Dockerfile.dev
    restart: "no"
    ports:
      - 8000:80
    volumes:
      - chissmiii_dist_vol:/var/www/html

volumes:
  chissmiii_dist_vol:
    name: chissmiii_dist_src
    driver: local
    driver_opts:
      device: ./dist
      type: none
      o: bind
