version: "3.7"

services:
  kirby:
    image: ${COMPOSE_PROJECT_NAME}_kirby:dev
    build:
      dockerfile: Dockerfile.dev
    container_name: ${MAIN_CONTAINER_NAME}-dev
    restart: "no"
    ports:
      - 8000:80
    volumes:
      - dist_vol:/var/www/html

volumes:
  dist_vol:
    name: ${COMPOSE_PROJECT_NAME}_dist_vol
    driver: local
    driver_opts:
      device: ${PWD}/dist
      type: none
      o: bind
