#!/bin/sh

# webserver user owns the webserver root dir
chown -R :www-data /var/www/html
chmod -R 775 /var/www/html

[ -d "npm_modules" ] && [ "$(ls -A node_modules)" ] && npm run build

# run CMD
exec "$@"